defaults: &defaults
  arrow_pass_host: 'http://arrow-pass.dev'
  client:
    app_key: '9164e3014bc4fec9a4054e0a68fbbc81'
    
development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  arrow_pass_host: 'http://qa.arrowpass.com'
