defaults: &defaults
  arrow_pass_host: 'http://arrow-pass.dev'
  client:
    app_key: '1111111111'
    
development:
  <<: *defaults

staging:
  <<: *defaults

production:
  client:
    app_key: '1111111111'
  arrow_pass_host: 'http://qa.arrowpass.com'
