development: &defaults
  adapter: postgresql
  encoding: utf8
  database: checker_development
  host: localhost
  pool: 5
  username: oleg
  password:

test: &test
  <<: *defaults
  database: checker_test

